version: '3'
services:
  frontend:
    build:
      context: ./front
    ports:
      - "4200:4200"
    networks:
      - mynetwork

  backend:
    build:
      context: ./back
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
